"use strict";
console.log("Age calculation");
var birth_year = 2005;
var current_year = 2024;
var age = current_year - birth_year;
console.log("My age is ", age);
console.log("percentage calculation");
var obt = 88;
var total = 100;
var percent = (obt / total) * 100;
console.log("Obtained marks=", obt);
console.log("Total marks=", total);
console.log("Percentage=", percent, "%");
