console.log("Age calculation");
var birth_year:number = 2005;
var current_year:number=2024;
var age:number=current_year-birth_year;
console.log("My age is ",age);
console.log("percentage calculation");
var obt:number=88;
var total:number=100;
var percent:number=(obt/total)*100;
console.log("Obtained marks=",obt);
console.log("Total marks=",total);
console.log("Percentage=",percent,"%");